# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bangazon_ultra', '0014_auto_20170302_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='producttype', to='bangazon_ultra.ProductTypes'),
        ),
    ]
