# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('payment_complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product_On_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_on_order', to='bangazon_storefront.Order')),
            ],
        ),
    ]
