# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangazon_storefront', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_account_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
