# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bangazon_storefront', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField(max_length=20)),
                ('payment_name', models.CharField(default='Unknown Payment Name', max_length=20)),
                ('expiration_date', models.CharField(max_length=10)),
                ('billing_address', models.CharField(max_length=35)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bangazon_storefront.Customer')),
            ],
        ),
    ]
