# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):


    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='bangazon_storefront.Customer'),
        ),
    ]
