# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangazon_storefront', '0005_auto_20170224_1800'),
        ('bangazon_storefront', '0002_productsmodel'),
    ]

    operations = [
    ]
