# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bangazon_storefront', '0006_merge_20170224_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bangazon_storefront.PaymentType'),
        ),
        migrations.AddField(
            model_name='product_on_order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_on_order', to='bangazon_storefront.ProductsModel'),
        ),
    ]
