# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangazon_storefront', '0007_auto_20170224_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='bangazon_storefront.Product_On_Order', to='bangazon_storefront.ProductsModel'),
        ),
    ]
