# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangazon_storefront', '0002_remove_customer_date_account_created'),
        ('bangazon_storefront', '0007_auto_20170224_1827'),
    ]

    operations = [
    ]
