# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangazon_storefront', '0005_merge_20170224_1752'),
        ('bangazon_storefront', '0007_auto_20170224_1827'),
    ]

    operations = [
    ]
