# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangazon_storefront', '0004_merge_20170224_2031'),
        ('bangazon_storefront', '0007_auto_20170224_1827'),
        ('bangazon_storefront', '0002_auto_20170223_1655'),
    ]

    operations = [
    ]
