# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangazon_storefront', '0008_order_products'),
        ('bangazon_storefront', '0008_merge_20170224_2059'),
    ]

    operations = [
    ]
