# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangazon_storefront', '0009_merge_20170227_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttype',
            name='billing_address',
            field=models.CharField(max_length=100),
        ),
    ]
