# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangazon_storefront', '0010_auto_20170227_1611'),
        ('bangazon_storefront', '0009_merge_20170227_1926'),
    ]

    operations = [
    ]
