# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 00:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bangazon_storefront', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='categoryId',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bangazon_storefront.ProductTypes'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='seller_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bangazon_storefront.Customer'),
        ),
    ]
